### ISSUE TITLE
Allow execution of a single file

### ISSUE THREAD

**Issue by rochacbruno** [ldjebran/robozilla#10]
```bash
brocha@localhost(rob63) :~/P/robozilla|master✓
➤ robozilla ../robottelo/tests/foreman/api/test_activationkey.py 
/home/brocha/Projects/robozilla
Traceback (most recent call last):
  File "/home/brocha/.virtualenvs/rob63/bin/robozilla", line 11, in <module>
    load_entry_point('robozilla', 'console_scripts', 'robozilla')()
  File "/home/brocha/Projects/robozilla/robozilla/scan.py", line 29, in main
    parser.parse(report=True)
  File "/home/brocha/Projects/robozilla/robozilla/parser.py", line 55, in parse
    for file_path in self.files_provider.get_files():
  File "/home/brocha/Projects/robozilla/robozilla/providers/fs.py", line 20, in get_files
    for name in sorted(os.listdir(scan_path)):
OSError: [Errno 20] Not a directory: '../robottelo/tests/foreman/api/test_activationkey.py'


```

**Comment by ldjebran** [comment]
implemented, please close on approval

**Comment by ldjebran** [comment]
implemented and merged, close
